### ISSUE TITLE
Promise after Catch should not resolve unless Catch handler returns a value

### ISSUE THREAD

**Issue by theJenix** [Real-Serious-Games/C-Sharp-Promise#56] opened 2017-12-06 04:50 UTC
This is referring to the new functionality in v2.0.  It looks like all Catch promises will now resolve, regardless of whether the Catch handler returns a value.  I may be missing something, but if that's true I think this is inconsistent with the Promises/A+ spec.  The Promises/A+ spec says the following about this (from https://promisesaplus.com/):
```
2.2.7 then must return a promise [3.3].

 promise2 = promise1.then(onFulfilled, onRejected);

2.2.7.1    If either onFulfilled or onRejected returns a value x, run the Promise Resolution Procedure [[Resolve]](promise2, x).
2.2.7.2    If either onFulfilled or onRejected throws an exception e, promise2 must be rejected with e as the reason.
``` 
Since onRejected doesn't have to return a value, 2.2.7.1 implies that you could have a situation where promise2 is not resolved.  I think the ability to chain promises after a Catch that are not automatically resolved should be present in this Promise library as well.

**Comment by RoryDungan** [comment] 2017-12-06 05:31
In the library we have taken "if onFulfilled or onRejected returns a value" to apply to all functions. In Javascript a function that does not explicitly return a value is the same as one that calls `return undefined`, so I believe that "returns a value" is meant to mean that the funcion has finished executing, as opposed to throwing an exception (2.2.7.2), or the value not being a function so not being executable (2.2.7.3 and 2.2.7.4). 

The current API should allow you to chain any kind of promise after a .Catch so do you think you could provide an example of what you're trying to do? 

Since Javascript ES6 added built-in support for promises we have been trying to reproduce as similar functionality to that as possible with a few additions like the PromiseTimer. We aim for the same code in Javascript and C# with our library to run in the same way so if you've found something that works in JS but not with this library that may be a bug.

**Comment by theJenix** [comment] 2017-12-12 18:43
Apologies for the delay.  I may have filed this issue prematurely: I tried playing with promises in a browser console window and it does indeed behave the way you describe.

What I'm trying to do is build a library function that does some asynchronous work; it returns a promise of some value and what I'd like to happen is, if the library function encounters an error, it stops resolving the promise chain (or put another way, consumers of the library function would not see a resolved promise).

Ex.
```
IPromise<Value> Foo() {
    return FooAsync().Catch(/*handle the error*/);
}

Foo().Then(v => /* only do something with v if the Catch didn't get called */);

```

In version 1.3.0, this pattern works (perhaps incorrectly), and my initial read of the changes in v2.0.0 suggests that either Then would get resolved if FooAsync threw an exception, or the return value of Foo would not be a promise of a Value which would limit my ability to encapsulate my library function.  Is there a recommended way use promises in this way?

**Comment by RoryDungan** [comment] 2017-12-13 00:29
I think you could achieve that result by creating a new promise and manually resolving it:
```
IPromise<Value> Foo() {
    var promise = new Promise<Value>();
    FooAsync()
        .Then(v => promise.Resolve(v))
        .Catch(/*handle the error*/);
    return promise;
}
```

However, I think this is generally not a good pattern because users of the library have no way to tell if the operation is still in progress or has failed. Generally the convention in this case would be to just reject the promise that is returned by `Foo` so that users of the library know when it has failed. Alternatively you could resolve it with `null` or use a [maybe monad](https://github.com/AndreyTsvetkov/Functional.Maybe) and resolve it with `Nothing`.

**Closed by RoryDungan** 2017-12-13 00:29 UTC

**Comment by theJenix** [comment] 2017-12-13 00:33
Thanks for the reply.  I was thinking of that, and actually, having Catch reject the new promise so that Foo callers can at least get a rejected promise, but for some reason it felt sub-optimal.  The other part I forgot to mention is my library uses the Catch handler to clean up some internals; without this, the caller would have to call back into to library from it's error handler, and that's kind of gross.  I think this gets me what I need with minimal grossness.

**Comment by RoryDungan** [comment] 2017-12-13 00:47
Ah yeah. Another option in that case would be to use a catch handler to clean up whatever you need but then after you've done that throw a new exception that the public API will be able to see. 

You can chain catches after each other and the second one will handle any exception thrown inside the first:
```
IPromise<Value> Foo() {
    return FooAsync()
        .Then(_ => throw new Exception("Exception 1"))
        .Catch(ex => {
            // do cleanup

            throw new Exception("Exception 2");
        });
}

// later in code
Foo()
    .Catch(ex => Console.Log(ex.Message)); // will print "Exception 2"
```

Hope that helps!
